#!/usr/local/bin/ruby

#restart the server 

alias :old_print :print
def print s
  old_print "#{s}\n"
  STDOUT.flush
end


print "updating from git"
`/home/consti/opt/bin/git pull origin master`

pid = nil
`ps x`.each_line { |line| pid = line.strip.split(" ").first  if line.include? 'mongrel' }

if pid
  print "stopping old server"
  print `kill #{pid}`
end

print "starting server"
print `export GEM_PATH=~/gems`
`./autostart.cgi`

print "all done"

print "run script/console production => TWITTER.post 'i fixded this'"
