#!/usr/bin/env ruby

# a simple twitter <-> urbantakeover gateway.
# no parsing happens here, we just pass all messages to the urban takeover message handler
# and return the result if there's any

require "xmpp4r"
require "net/http"
require "cgi"
require "iconv"
require "yaml"

API_CONFIG = YAML.load(File.open("config/private_api.yml"))

def dispatch_to_rails user, msg
  req = Net::HTTP.post_form(URI.parse(API_CONFIG['server']),
                                {'user' => user, 'message' => msg, 'key' => API_CONFIG['api_key']})

  if req.body.include? "Exception caught" # very quick, very dirty
    return "sorry, something went terribly wrong on the server. will try to fix it."
  else
    return req.body[0...150]
  end
end


print dispatch_to_rails("oneup", "claim metalab")